### ISSUE TITLE
SSLProtocolException

### ISSUE THREAD

**Issue by omidshojaee** [kittoku/Minimum-VPN-Client-for-SoftEther-VPN#10]
I get this error when trying to connect to a fresh install of the SoftEther server v4.39 Build 9772:

```
[2022-10-19 11:03:07.047] Connecting has been attempted
[2022-10-19 11:03:11.494] An exception/error has been occurred:
javax.net.ssl.SSLProtocolException: Read error: ssl=0x7afd9b4308: Failure in SSL library, usually a protocol error
error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION (external/boringssl/src/ssl/tls_record.cc:592 0x7afd938008:0x00000001)
	at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
	at com.android.org.conscrypt.NativeSsl.read(NativeSsl.java:407)
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:579)
	at kittoku.mvc.service.teminal.tcp.TCPTerminal.receiveStream(TCPTerminal.kt:99)
	at kittoku.mvc.service.teminal.tcp.TCPTerminal.extendStream(TCPTerminal.kt:122)
	at kittoku.mvc.service.teminal.tcp.TCPTerminal.ensureSomeFrame(TCPTerminal.kt:262)
	at kittoku.mvc.service.teminal.tcp.TCPTerminal.access$ensureSomeFrame(TCPTerminal.kt:29)
	at kittoku.mvc.service.teminal.tcp.TCPTerminal$ensureSomeFrame$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

I have no issues connecting on PC.

**Comment by kittoku** [comment]
This is a known issue (#1 ).

**Comment by omidshojaee** [comment]
For Linux we always build from source. There's no binary so this issue is related to something else?

**Comment by uchar** [comment]
I have same problem , this issue surely is not related to building from the source code , because I build it and having same problem .
@omidshojaee Did you find any solution for this ?

**Comment by kittoku** [comment]
Have you tried compling from the source? I didn't ment building from the source is linking the static libraries. But, yes, I admit the possibility of my bad coding causing this problem. I rather hope that's true, so this issue could be fixed without depending on other softwares.

By the way, even if this app works, the capability is very limited and its behavior is unstable. So if you want an immediate solution, I recommend other VPN protocol like OpenVPN or SSTP.
