### ISSUE TITLE
crashed while connecting

### ISSUE THREAD

**Issue by rezazealott** [kittoku/Minimum-VPN-Client-for-SoftEther-VPN#11]
hi
when we try to connect it crashed and closed .

[2022-11-10 13:52:36.505] Connecting has been attempted
[2022-11-10 13:52:37.881] An exception/error has been occurred:
kittoku.mvc.debug.MvcException: SOFTETHER_AUTHENTICATION_FAILED
	at kittoku.mvc.debug.ExceptionKt.assertOrThrow(exception.kt:16)
	at kittoku.mvc.service.client.softether.SoftEtherClient.uploadProperties(SoftEtherClient.kt:165)
	at kittoku.mvc.service.client.softether.SoftEtherClient.access$uploadProperties(SoftEtherClient.kt:21)
	at kittoku.mvc.service.client.softether.SoftEtherClient$uploadProperties$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
Caused by: kittoku.mvc.debug.AssertException: 
	at kittoku.mvc.debug.ExceptionKt.assertAlways(exception.kt:8)
	at kittoku.mvc.service.client.softether.SoftEtherClient$uploadProperties$2.invoke(SoftEtherClient.kt:167)
	at kittoku.mvc.service.client.softether.SoftEtherClient$uploadProperties$2.invoke(SoftEtherClient.kt:165)
	at kittoku.mvc.debug.ExceptionKt.assertOrThrow(exception.kt:14)
	... 8 more

**Comment by p3im4n** [comment]
same problrm
