### ISSUE TITLE
SOFTETHER_AUTHENTICATION_FAILED

### ISSUE THREAD

**Issue by Pillen1** [kittoku/Minimum-VPN-Client-for-SoftEther-VPN#15]
Whenever I've tried to connect a SoftEther server, it won't connect and giving this error:
SOFTETHER_AUTHENTICATION_FAILED

I'm using Android 12

(My SoftEther server that I've tried to connect has "RADIUS - NT Domain Authentication" as a AUTH Type which i can easily connect to it via Official SoftEther Client on Windows.)

Here's the log:
[2023-10-31 11:12:43.660] Connecting has been attempted
[2023-10-31 11:12:44.465] An exception/error has been occurred:
kittoku.mvc.debug.MvcException: SOFTETHER_AUTHENTICATION_FAILED
	at kittoku.mvc.debug.ExceptionKt.assertOrThrow(exception.kt:16)
	at kittoku.mvc.service.client.softether.SoftEtherClient.uploadProperties(SoftEtherClient.kt:165)
	at kittoku.mvc.service.client.softether.SoftEtherClient.access$uploadProperties(SoftEtherClient.kt:21)
	at kittoku.mvc.service.client.softether.SoftEtherClient$uploadProperties$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
Caused by: kittoku.mvc.debug.AssertException: 
	at kittoku.mvc.debug.ExceptionKt.assertAlways(exception.kt:8)
	at kittoku.mvc.service.client.softether.SoftEtherClient$uploadProperties$2.invoke(SoftEtherClient.kt:167)
	at kittoku.mvc.service.client.softether.SoftEtherClient$uploadProperties$2.invoke(SoftEtherClient.kt:165)
	at kittoku.mvc.debug.ExceptionKt.assertOrThrow(exception.kt:14)

**Comment by JalalKhanSL** [comment]
I have the same issue, did you solve the it, I`m trying to use it on Android 14.
