### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by MatAtBread** [kittoku/Minimum-VPN-Client-for-SoftEther-VPN#4]
I'm having problems with authentication. Running SE on a Raspberry Pi model 3+, successfully using L2TP/IPSec for ages. However L2TP/IPSec support has been removed from Android 12 in favour of IKEv2 (not supported by SoftEther). I've configured the OpenVPN support, and it works (alongside the L2TP/IPSec protocol)  from Android 12, but is very slow (maybe 4Mbps, compared to 15-20 I'd get with L2TP).

I've installed the same CA cert in the server and Android device, and it now connects, however authentication fails (log below).

Any ideas? The same user account works with L2TP/IPSec and OpenVPN.

Incidentally, now L2TP support has gone from Android, IKEv2 is absent from SoftEther and OpenVPN is very slow, this project might be very useful!

```
[2021-11-02 14:05:07.291] Connecting has been attempted
[2021-11-02 14:05:07.552] An exception/error has been occurred:
kittoku.mvc.debug.MvcException: SOFTETHER_AUTHENTICATION_FAILED
	at kittoku.mvc.debug.ExceptionKt.assertOrThrow(exception.kt:16)
	at kittoku.mvc.service.client.softether.SoftEtherClient.uploadProperties(SoftEtherClient.kt:165)
	at kittoku.mvc.service.client.softether.SoftEtherClient.access$uploadProperties(SoftEtherClient.kt:21)
	at kittoku.mvc.service.client.softether.SoftEtherClient$uploadProperties$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
Caused by: kittoku.mvc.debug.AssertException: 
	at kittoku.mvc.debug.ExceptionKt.assertAlways(exception.kt:8)
	at kittoku.mvc.service.client.softether.SoftEtherClient$uploadProperties$2.invoke(SoftEtherClient.kt:167)
	at kittoku.mvc.service.client.softether.SoftEtherClient$uploadProperties$2.invoke(SoftEtherClient.kt:165)
	at kittoku.mvc.debug.ExceptionKt.assertOrThrow(exception.kt:14)
	... 8 more

```

**Comment by MatAtBread** [comment]
I noticed the username is being defaulted (for test purposes?) here: https://github.com/kittoku/Minimum-VPN-Client-for-SoftEther-VPN/blob/main/app/src/main/java/kittoku/mvc/service/client/softether/SoftEtherClient.kt#L107

I've now set this to `bridge.clientUsername`, and the error has changed. Now I get:

```
[2021-11-02 18:29:53.003] Connecting has been attempted
[2021-11-02 18:30:02.172] An exception/error has been occurred:
javax.net.ssl.SSLProtocolException: Read error: ssl=0x770d9c2318: Failure in SSL library, usually a protocol error
error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION (external/boringssl/src/ssl/tls_record.cc:594 0x772d9a0f78:0x00000001)
	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:569)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:858)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797)
	at kittoku.mvc.service.teminal.tcp.TCPTerminal.receiveStream(TCPTerminal.kt:99)
	at kittoku.mvc.service.teminal.tcp.TCPTerminal.extendStream(TCPTerminal.kt:122)
	at kittoku.mvc.service.teminal.tcp.TCPTerminal.ensureSomeFrame(TCPTerminal.kt:262)
	at kittoku.mvc.service.teminal.tcp.TCPTerminal.access$ensureSomeFrame(TCPTerminal.kt:29)
	at kittoku.mvc.service.teminal.tcp.TCPTerminal$ensureSomeFrame$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)

```

**Comment by MatAtBread** [comment]
I think the above case is a duplicate of https://github.com/kittoku/Minimum-VPN-Client-for-SoftEther-VPN/issues/1

I rebuilt the ARM binary on the RPi3+, and I now get another error, even after enabling the SecureNAT & DHCP function for the VirtualHUB.

```
[2021-11-02 20:21:49.302] Connecting has been attempted
[2021-11-02 20:22:19.724] An exception/error has been occurred:
kittoku.mvc.debug.MvcException: DHCP_NEGOTIATION_TIMEOUT
	at kittoku.mvc.service.client.ControlClient$launchJobMain$1.invokeSuspend(ControlClient.kt:107)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.ResumeModeKt.resumeUninterceptedWithExceptionMode(ResumeMode.kt:56)
	at kotlinx.coroutines.TimeoutCoroutine.afterCompletionInternal(Timeout.kt:98)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:310)
	at kotlinx.coroutines.JobSupport.tryFinalizeFinishingState(JobSupport.kt:236)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:849)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:811)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:787)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

I guess this means:
* The correct auth is now being provided (not the "debug" user)
* The version on OpenSSL used to compile the binary works with the Android SSL stack
* SecureNAT / DHCP isn't working as expected. 

I've never used the DHCP within SoftEther before, so I don't (yet) know how to tell if it works

**Comment by MatAtBread** [comment]
The good news is that I manually set the "optional" part of the SecureNAT Virtual DHCP settings, and now it connects.

The bad news is the throughput is not great - about 3Mbps - comparable with OpenVPN but much slower than L2TP/IPSec.

I guess I'll either wait for SE to add IKEv2 (see https://github.com/SoftEtherVPN/SoftEtherVPN/issues/13 - now live for 7 years), or consider changing servers

**Comment by MatAtBread** [comment]
And finally, for whatever reason, clients connected via the SoftEther protocol can't access services on the same host. I achieved this by setting up br0 to link eth0 and tap_vpn when the server starts up, but this Linux bridge doesn't seem to work with the SoftEther protocol. 

The same client connected via the OpenVPN client & protocol at least does allow this, so I'll stick with that for now.

The project is a very useful one, and perhaps with further development it would solve the issue created by Android 12 not supporting L2TP

**Comment by kittoku** [comment]
Thank you @MatAtBread. Your contribution is very helpful!

>I noticed the username is being defaulted (for test purposes?) here

This part is fatal. I'm fixing soon. 

> I manually set the "optional" part of the SecureNAT Virtual DHCP settings

Could you show me what you did? It will help users stuck with the same problem. Please ignore me if it's cannot be public for some reason.

> The bad news is the throughput is not great

If you are using "UDP Acceleration", I noticed the issue. My implementation may be not good. I can come up with three solution.

1.  If you don't use "VPN Azure",  disable "UDP Acceleration" option.
2.  With a SSTP client, theoretically you can achieve the same performance as solution 1.
3.  Decreasing MTU size could improve UDP Acceleration performance. But I don't think it brings drastic change.

> clients connected via the SoftEther protocol can't access services on the same host

Sorry, but I cannot think of what caused this. Ethernet and IP stack implementation of this app is very simplified for development. So maybe this app doesn't work for services needing a bit complicated networking.

**Comment by MatAtBread** [comment]
> > I manually set the "optional" part of the SecureNAT Virtual DHCP settings

> Could you show me what you did? It will help users stuck with the same problem. Please ignore me if it's cannot be public for some reason.

From the "Manage Hub", click on "Virtual NAT...", click on "SecureNAT configuration", fill in the "Options applied to clients" with _valid_ values, and in my case I also updated the "Virtual Host's NI Settings" to ensure the pre-filled IP was in the same subnet as my LAN.

![image](https://user-images.githubusercontent.com/2789075/140044898-bce6c367-071a-40b6-9fe2-607327899050.png)

**Comment by MatAtBread** [comment]
> > clients connected via the SoftEther protocol can't access services on the same host

> Sorry, but I cannot think of what caused this. Ethernet and IP stack implementation of this app is very simplified for development. So maybe this app doesn't work for services needing a bit complicated networking (This app sends all IP packets only to default gateway).

I think this might be more subtle, and I'll have a deeper look later. On Linux (my server platform), a bound h/w interface (like eth0) can't send to itself - only loopback interfaces can. The SE manual suggests binding to a tap on a bridge with the ethernet (or wifi or whatever). My `ifconfig` looks like this:

```
br0: flags=4419<UP,BROADCAST,RUNNING,PROMISC,MULTICAST>  mtu 1500
        inet 192.168.0.3  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 fe80::ba27:ebff:fe7e:9f13  prefixlen 64  scopeid 0x20<link>
        ether 5e:c0:60:25:65:1c  txqueuelen 1000  (Ethernet)
        RX packets 2301941219  bytes 175303829799 (163.2 GiB)
        RX errors 0  dropped 2206453  overruns 0  frame 0
        TX packets 2492022724  bytes 553585610582 (515.5 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4419<UP,BROADCAST,RUNNING,PROMISC,MULTICAST>  mtu 1500
        ether b8:27:eb:7e:9f:13  txqueuelen 1000  (Ethernet)
        RX packets 2580733339  bytes 4116934141 (3.8 GiB)
        RX errors 168  dropped 12617  overruns 0  frame 158
        TX packets 2623940265  bytes 3649882776 (3.3 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 1764970  bytes 128193526 (122.2 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1764970  bytes 128193526 (122.2 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

tap_vpn: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::5cc0:60ff:fe25:651c  prefixlen 64  scopeid 0x20<link>
        ether 5e:c0:60:25:65:1c  txqueuelen 1000  (Ethernet)
        RX packets 243382  bytes 36743333 (35.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 394648  bytes 112792864 (107.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

Note: this is all at the _server_. This has nothing to do with the client. It's quite likely a consequence of enabling the Virtual NAT/DHCP or some other change I made to the SE config when trying to get the VPN client to work.

**Comment by MatAtBread** [comment]
Hmmm.....I may have been on the wrong track with the DHCP settings. I re-enabled it today and it's failing with the `DHCP_NEGOTIATION_TIMEOUT` exception again, so I probably have to do some more digging.
