### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by Evolve6996** [kittoku/Minimum-VPN-Client-for-SoftEther-VPN#7]
hello 
thanks for the app ❤️  i have some question
1-i should only connect to my server via VPN Azure?

---------------

2-i have a softether vpn server but I cannot connect to it using this app:

[2022-04-22 22:12:53.337] Connecting has been attempted
[2022-04-22 22:12:53.679] An exception/error has been occurred:
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:355)
	at kittoku.mvc.service.teminal.tcp.TCPTerminal.<init>(TCPTerminal.kt:61)
	at kittoku.mvc.service.client.ControlClient$launchJobMain$1.invokeSuspend(ControlClient.kt:66)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:659)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:537)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:493)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:416)
	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:337)
	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:203)
	at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:592)
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:351)
	... 7 more
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	... 18 more

-------

3-i wanna use softether vpn protocol on android can i use this app ?

**Comment by kittoku** [comment]
1: Connecting via VPN Azure is not necessary.
2: Did you install server's certificate? Please chech if you can connect to your server with other apps.
3: Yes, you can. But there is a lot of limitations as README says.

I am afraid this is an inactive project and the app is not for end users yet. So I highly recommend you use other apps.

**Comment by Evolve6996** [comment]
> 1: Connecting via VPN Azure is not necessary. 2: Did you install the server's certificate? Please check if you can connect to your server with other apps. 3: Yes, you can. But there are a lot of limitations as README says.
> 
> I am afraid this is an inactive project and the app is not for end-users yet. So I highly recommend you use other apps.

1-i have sstp server which connects via ms sstp android app fine on my phone but I cannot connect to it on windows 10 it says the certificate expired or something but maybe this app has the same problem where is my server certificate for import to my phone?

2-i know but there are apps for OpenVPN and sstp but couldn't find any free app for softether protocol on android do you know any?
thanks 💟

**Comment by kittoku** [comment]
If the other app works for you, why you need this app? I am sure that this app is more unstable and has less features than any other app.

**Comment by Evolve6996** [comment]
> If the other app works for you, why you need this app? I am sure that this app is more unstable and has less features than any other app.

as I said I wanna connect to **softether VPN protocol** on android, not OpenVPN or sstp and other protocols you can establish using softether VPN server
