### ISSUE TITLE
Trust anchor for certification path not found

### ISSUE THREAD

**Issue by majid23** [kittoku/Minimum-VPN-Client-for-SoftEther-VPN#9]
There is an error during connection in TCPTerminal.kt line 63: socket.startHandshake()
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

The server is ok and I can connect from softether client manager.

**Comment by omidshojaee** [comment]
You need a valid certificate installed on the server. Use ```certbot certonly``` and then ```ServerCertSet``` command of the ```vpncmd```

**Comment by uchar** [comment]
You can also use this guide to create a certificate too (Step 10): https://www.digitalocean.com/community/tutorials/how-to-setup-a-multi-protocol-vpn-server-using-softether 
After creating the certificate, download it and install it on your phone (depending on the android version, it's somewhere in the setting menu  usually in Advanced settings. Encryption & credentials )

**Comment by aicochow** [comment]
I am trying this ,give me this error
```
[2023-01-21 21:10:35.567] Connecting has been attempted
[2023-01-21 21:10:36.646] An exception/error has been occurred:
javax.net.ssl.SSLProtocolException: Read error: ssl=0xea234398: Failure in SSL library, usually a protocol error
error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION (external/boringssl/src/ssl/tls_record.cc:587 0xe4e56278:0x00000001)
	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:568)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:849)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:815)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:788)
	at kittoku.mvc.service.teminal.tcp.TCPTerminal.receiveStream(TCPTerminal.kt:99)
	at kittoku.mvc.service.teminal.tcp.TCPTerminal.extendStream(TCPTerminal.kt:122)
	at kittoku.mvc.service.teminal.tcp.TCPTerminal.ensureSomeFrame(TCPTerminal.kt:262)
	at kittoku.mvc.service.teminal.tcp.TCPTerminal.access$ensureSomeFrame(TCPTerminal.kt:29)
	at kittoku.mvc.service.teminal.tcp.TCPTerminal$ensureSomeFrame$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```
